declare module "@babel/core";
declare module "@babel/types";
declare module "@babel/parser";
declare module "@babel/traverse";
declare module "@babel/generator";
declare module "@babel/code-frame";
declare module "@babel/plugin-syntax-typescript";
declare module "@babel/plugin-transform-modules-commonjs";
declare module "@babel/plugin-transform-typescript";
