import fs from "fs";
import path from "path";

import * as tagsTranslator from "../../translator";
import type { TestConfig } from "../main.test";
import { createServerRunner } from "../utils/bundle";
import {
  type Browser,
  createHostRunner,
  type Render,
  renderCSR,
  renderSSR,
  type Steps,
} from "../utils/render";
import { wait } from "../utils/resolve";
import { type Case, type Node, print, type StepSpec } from "./generate";

export interface Failure {
  oracle: "compile" | "render" | "ssr/csr" | "debug/optimize";
  message: string;
}

// Shrinking keeps a candidate only if it fails the same way: an error with
// the same first line, or the same oracle's comparison.
export function sameFailure(a: Failure, b: Failure | undefined) {
  return (
    a.oracle === b?.oracle &&
    (a.oracle !== "render" || firstLine(a.message) === firstLine(b.message))
  );
}

// Every oracle here needs no expected output: the case must compile, render
// without errors, log alike when resumed and client rendered, and log alike
// in both modes.
export async function check(
  generated: Case,
  dir: string,
): Promise<Failure | undefined> {
  writeCase(generated, dir);
  // The client renders `<await>` content later than the server streams it,
  // so an async case waits after every step and compares where both settle.
  const async = isAsync(generated);
  const config: TestConfig = { steps: toSteps(generated) };
  // A case that updates input renders under a host holding that input, so
  // the updates also apply after resume.
  const hosted = generated.steps.some((step) => "input" in step);
  const browsers: Browser[] = [];
  let cleanup = () => {};
  try {
    const renders = await Promise.all(
      [false, true].map(async (optimize) => {
        const opts = compileOpts(dir, optimize);
        const page = await (
          hosted
            ? createHostRunner(dir, opts)
            : createServerRunner(dir, { template: "./template.marko" }, opts)
        ).catch((error: Error) => {
          throw Object.assign(error, { oracle: "compile" });
        });
        const render: Render = {
          config,
          page: () => Promise.resolve(page),
          browsers,
          settle: async,
          hosted,
        };
        return render;
      }),
    );
    const [debug, optimize] = renders;
    cleanup = () =>
      renders.forEach(async (render) => (await render.page()).disposeServer());
    const ssr = await renderSSR(debug);
    const csr = await renderCSR(debug);
    const optimized = await renderSSR(optimize);
    const logs = {
      ssr: comparable(ssr.tracker.getLogs()),
      csr: comparable(csr.tracker.getLogs()),
    };
    if (async ? ssr.settled !== csr.settled : logs.ssr !== logs.csr) {
      return {
        oracle: "ssr/csr",
        message: diff(
          async ? ssr.settled : logs.ssr,
          async ? csr.settled : logs.csr,
        ),
      };
    }
    if (optimized.tracker.getLogs() !== ssr.tracker.getLogs()) {
      return {
        oracle: "debug/optimize",
        message: diff(ssr.tracker.getLogs(), optimized.tracker.getLogs()),
      };
    }
  } catch (error) {
    return {
      oracle: (error as { oracle?: "compile" }).oracle ?? "render",
      message: String((error as Error).stack ?? error),
    };
  } finally {
    cleanup();
    // A render still queued as a microtask must not run in a closed window.
    await new Promise((resolve) => setImmediate(resolve));
    for (const browser of browsers) browser.window.close();
  }
}

export function writeCase(generated: Case, dir: string) {
  fs.mkdirSync(path.join(dir, "tags"), { recursive: true });
  fs.writeFileSync(path.join(dir, "template.marko"), print(generated.template));
  fs.writeFileSync(
    path.join(dir, "tags", "child.marko"),
    print(generated.child),
  );
}

// A fixture reproducing the case, ready to move into `fixtures/<area>/`.
export function writeFixture(generated: Case, failure: Failure, dir: string) {
  writeCase(generated, dir);
  const steps = [
    JSON.stringify(generated.input),
    ...sequence(generated).map((step) =>
      step === "wait"
        ? step
        : "click" in step
          ? `click(${JSON.stringify(step.click)})`
          : JSON.stringify(step.input),
    ),
  ];
  const imports = [
    `import type { TestConfig } from "../../../main.test";`,
    steps.includes("wait") && `import { wait } from "../../../utils/resolve";`,
    steps.some((step) => step.startsWith("click(")) &&
      `import { click } from "../../../utils/steps";`,
  ].filter(Boolean);
  fs.writeFileSync(
    path.join(dir, "test.ts"),
    `${imports.join("\n")}

// Generated by \`pnpm run fuzz -- --seed ${generated.seed}\` (${failure.oracle}).
export const config: TestConfig = {
  steps: [${steps.join(", ")}],
};
`,
  );
  fs.writeFileSync(path.join(dir, "failure.txt"), failure.message);
}

function toSteps(generated: Case): Steps {
  return [
    generated.input,
    ...sequence(generated).map((step) =>
      step === "wait" ? wait : "click" in step ? tap(step.click) : step.input,
    ),
  ];
}

// An async case waits for pending work after the first render and each step.
function sequence(generated: Case) {
  const async = isAsync(generated);
  const steps: (StepSpec | "wait")[] = async ? ["wait"] : [];
  for (const step of generated.steps) {
    steps.push(step);
    if (async) steps.push("wait");
  }
  return steps;
}

function isAsync(generated: Case) {
  return [generated.template, generated.child].some(hasAwait);
}

function firstLine(message: string) {
  return message.slice(0, message.indexOf("\n") >>> 0);
}

// Unlike `utils/steps` › click, a missing button is no failure: a generated
// click may target content its branch no longer renders.
function tap(selector: string) {
  return Object.assign(
    (document: Document) => {
      document.querySelector<HTMLElement>(selector)?.click();
    },
    { label: `click(${JSON.stringify(selector)})` },
  );
}

function compileOpts(dir: string, optimize: boolean) {
  return {
    translator: tagsTranslator,
    cache: new Map(),
    writeVersionComment: false,
    babelConfig: {
      babelrc: false,
      configFile: false,
      browserslistConfigFile: false,
    },
    optimize,
    optimizeKnownTemplates: optimize
      ? [
          path.join(dir, "template.marko"),
          path.join(dir, "tags", "child.marko"),
        ]
      : undefined,
  };
}

// The server writes adjacent text as one node where the client keeps several,
// so the resumed and client logs compare without their mutation records.
function comparable(log: string) {
  return log.replace(/\n## Change\n```\n[^`]*```/g, "");
}

function diff(expected: string, actual: string) {
  const a = expected.split("\n");
  const b = actual.split("\n");
  let i = 0;
  while (i < a.length && a[i] === b[i]) i++;
  return [
    ...a.slice(Math.max(0, i - 3), i).map((line) => `  ${line}`),
    ...a.slice(i, i + 6).map((line) => `- ${line}`),
    ...b.slice(i, i + 6).map((line) => `+ ${line}`),
  ].join("\n");
}

function hasAwait(nodes: Node[]): boolean {
  return nodes.some(
    (node) =>
      node.kind === "await" ||
      ("children" in node && hasAwait(node.children)) ||
      (node.kind === "if" && !!node.otherwise && hasAwait(node.otherwise)),
  );
}
