export enum AccessorPrefix {
  BranchScopes = "BranchScopes:",
  BranchScopesByKey = "BranchScopesByKey:",
  ClosureScopes = "ClosureScopes:",
  ClosureSignalIndex = "ClosureSignalIndex:",
  ConditionalRenderer = "ConditionalRenderer:",
  ControlledHandler = "ControlledHandler:",
  ControlledType = "ControlledType:",
  ControlledValue = "ControlledValue:",
  DynamicPlaceholderLastChild = "DynamicPlaceholderLastChild:",
  EventAttributes = "EventAttributes:",
  Getter = "Getter:",
  LifecycleAbortController = "LifecycleAbortController:",
  Promise = "Promise:",
  TagVariableChange = "TagVariableChange:",
}

export enum AccessorProp {
  Global = "$global",
  Owner = "_",
  AbortControllers = "#AbortControllers",
  AbortScopes = "#AbortScopes",
  Args = "#Args",
  BranchAccessor = "#BranchAccessor",
  BranchScopes = "#BranchScopes",
  CatchContent = "#CatchContent",
  ClosestBranch = "#ClosestBranch",
  ClosestBranchId = "#ClosestBranchId",
  Creating = "#Creating",
  Destroyed = "#Destroyed",
  Effects = "#Effects",
  EndNode = "#EndNode",
  Id = "#Id",
  LoopKey = "#LoopKey",
  ParentBranch = "#ParentBranch",
  PendingAsyncCount = "#PendingAsyncCount",
  PlaceholderBranch = "#PlaceholderBranch",
  PlaceholderContent = "#PlaceholderContent",
  Renderer = "#Renderer",
  StartNode = "#StartNode",
  TagVariable = "#TagVariable",
  TagVariableChange = "#TagVariableChange",
}
