export enum AccessorPrefix {
  ClosureScopes = "A",
  ClosureSignalIndex = "B",
  ConditionalRenderer = "C",
  ConditionalScope = "D",
  ControlledHandler = "E",
  ControlledType = "F",
  ControlledValue = "G",
  DynamicPlaceholderLastChild = "H",
  EventAttributes = "I",
  Getter = "J",
  LifecycleAbortController = "K",
  LoopScopeArray = "L",
  LoopScopeMap = "M",
  Promise = "N",
  TagVariableChange = "O",
}

export enum AccessorProp {
  Global = "$",
  Owner = "_",
  AbortControllers = "A",
  AbortScopes = "B",
  Args = "C",
  BranchAccessor = "D",
  BranchScopes = "E",
  CatchContent = "F",
  ClosestBranch = "G",
  ClosestBranchId = "H",
  Creating = "I",
  Destroyed = "J",
  Effects = "K",
  EndNode = "L",
  Id = "M",
  ParentBranch = "N",
  PendingAsyncCount = "O",
  PlaceholderBranch = "P",
  PlaceholderContent = "Q",
  Renderer = "R",
  StartNode = "S",
  TagVariable = "T",
  TagVariableChange = "U",
}
