export enum AccessorPrefix {
  BranchScopes = "A",
  BranchScopesByKey = "B",
  ClosureScopes = "C",
  ClosureSignalIndex = "D",
  ConditionalRenderer = "E",
  ControlledHandler = "F",
  ControlledType = "G",
  ControlledValue = "H",
  DynamicPlaceholderLastChild = "I",
  EventAttributes = "J",
  Getter = "K",
  LifecycleAbortController = "L",
  Promise = "M",
  TagVariableChange = "N",
}

export enum AccessorProp {
  Global = "$",
  Owner = "_",
  AbortControllers = "A",
  AbortScopes = "B",
  Args = "C",
  BranchAccessor = "D",
  BranchScopes = "E",
  CatchContent = "F",
  ClosestBranch = "G",
  ClosestBranchId = "H",
  Creating = "I",
  Destroyed = "J",
  Effects = "K",
  EndNode = "L",
  Id = "M",
  LoopKey = "N",
  ParentBranch = "O",
  PendingAsyncCount = "P",
  PlaceholderBranch = "Q",
  PlaceholderContent = "R",
  Renderer = "S",
  StartNode = "T",
  TagVariable = "U",
  TagVariableChange = "V",
}
